name: generative_chatbot
channels:
  - pytorch-nightly
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aiohttp=3.8.5
  - aiosignal=1.3.1
  - async-timeout=4.0.2
  - attrs=23.1.0
  - aws-c-auth=0.7.0
  - aws-c-cal=0.6.0
  - aws-c-common=0.8.23
  - aws-c-compression=0.2.17
  - aws-c-event-stream=0.3.1
  - aws-c-http=0.7.11
  - aws-c-io=0.13.28
  - aws-c-mqtt=0.8.14
  - aws-c-s3=0.3.13
  - aws-c-sdkutils=0.1.11
  - aws-checksums=0.1.16
  - aws-crt-cpp=0.20.3
  - aws-sdk-cpp=1.10.57
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.7.22
  - certifi=2023.7.22
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - click=8.1.6
  - colorama=0.4.6
  - cryptography=38.0.4
  - cuda-version=11.8
  - cudatoolkit=11.8.0
  - cudnn=8.9.2.26
  - dataclasses=0.8
  - datasets=2.13.1
  - dill=0.3.6
  - filelock=3.9.0
  - frozenlist=1.4.0
  - fsspec=2023.6.0
  - gflags=2.2.2
  - glog=0.6.0
  - huggingface_hub=0.16.4
  - icu=72.1
  - idna=3.4
  - importlib-metadata=6.8.0
  - importlib_metadata=6.8.0
  - jinja2=3.1.2
  - joblib=1.3.0
  - keyutils=1.6.1
  - krb5=1.21.1
  - ld_impl_linux-64=2.38
  - libabseil=20230125.3
  - libarrow=12.0.1
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.2.1
  - libedit=3.1.20221030
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.4
  - libgcc-ng=13.1.0
  - libgfortran-ng=13.1.0
  - libgfortran5=13.1.0
  - libgoogle-cloud=2.12.0
  - libgrpc=1.54.2
  - libhwloc=2.9.1
  - libiconv=1.17
  - liblapack=3.9.0
  - libmagma=2.7.1
  - libmagma_sparse=2.7.1
  - libnghttp2=1.52.0
  - libnuma=2.0.16
  - libopenblas=0.3.23
  - libprotobuf=3.21.12
  - libssh2=1.11.0
  - libstdcxx-ng=13.1.0
  - libthrift=0.18.1
  - libutf8proc=2.8.0
  - libuuid=1.41.5
  - libxml2=2.11.4
  - libzlib=1.2.13
  - llvm-openmp=16.0.6
  - lz4-c=1.9.4
  - magma=2.7.1
  - markupsafe=2.1.3
  - mkl=2022.2.1
  - mpmath=1.2.1
  - multidict=6.0.4
  - nccl=2.18.3.1
  - ncurses=6.4
  - networkx=3.1
  - numpy=1.25.1
  - openssl=3.1.1
  - orc=1.9.0
  - packaging=22.0
  - pandas=2.0.3
  - pip=23.2.1
  - pyarrow=12.0.1
  - pycparser=2.21
  - pyopenssl=23.2.0
  - pysocks=1.7.1
  - python=3.11.4
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python-xxhash=3.2.0
  - python_abi=3.11
  - pytorch-gpu=2.0.0
  - pytz=2023.3
  - pyyaml=6.0
  - rdma-core=28.9
  - re2=2023.03.02
  - readline=8.2
  - regex=2023.6.3
  - requests=2.28.1
  - responses=0.18.0
  - s2n=1.3.46
  - sacremoses=0.0.53
  - safetensors=0.3.1
  - setuptools=68.0.0
  - six=1.16.0
  - sleef=3.5.1
  - snappy=1.1.10
  - sqlite=3.41.2
  - sympy=1.12
  - tbb=2021.9.0
  - tk=8.6.12
  - tokenizers=0.13.3
  - tqdm=4.65.0
  - transformers=4.31.0
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - tzdata=2023c
  - ucx=1.14.1
  - urllib3=1.26.14
  - wheel=0.38.4
  - xxhash=0.8.1
  - xz=5.4.2
  - yaml=0.2.5
  - yarl=1.9.2
  - zipp=3.16.2
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - accelerate==0.21.0
      - aiofiles==23.1.0
      - altair==5.0.1
      - annotated-types==0.5.0
      - anyio==3.7.1
      - blessed==1.20.0
      - cmake==3.27.0
      - contourpy==1.1.0
      - cycler==0.11.0
      - evaluate==0.4.0
      - fastapi==0.100.1
      - ffmpy==0.3.1
      - fonttools==4.41.1
      - gpustat==1.1
      - gradio==3.39.0
      - gradio-client==0.3.0
      - h11==0.14.0
      - httpcore==0.17.3
      - httpx==0.24.1
      - jsonschema==4.18.4
      - jsonschema-specifications==2023.7.1
      - kiwisolver==1.4.4
      - linkify-it-py==2.0.2
      - lit==16.0.6
      - markdown-it-py==2.2.0
      - matplotlib==3.7.2
      - mdit-py-plugins==0.3.3
      - mdurl==0.1.2
      - multiprocess==0.70.14
      - mypy-extensions==1.0.0
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-ml-py==12.535.77
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nvtx-cu11==11.7.91
      - orjson==3.9.2
      - pillow==10.0.0
      - psutil==5.9.5
      - pydantic==2.1.1
      - pydantic-core==2.4.0
      - pydub==0.25.1
      - pyparsing==3.0.9
      - pyre-extensions==0.0.29
      - python-multipart==0.0.6
      - referencing==0.30.0
      - rpds-py==0.9.2
      - semantic-version==2.10.0
      - sniffio==1.3.0
      - starlette==0.27.0
      - toolz==0.12.0
      - torch==2.0.1
      - triton==2.0.0
      - typing-inspect==0.9.0
      - uc-micro-py==1.0.2
      - uvicorn==0.23.2
      - wcwidth==0.2.6
      - websockets==11.0.3
      - xformers==0.0.20
